@host=http://localhost:3000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjUwNTM3NjUwLCJleHAiOjE2NTA1NDEyNTB9.L9zIolIbi5tkkRq22V-lUyTBnqNjmZHgTd10IEAYbg8

POST {{host}}/auth/signin
Content-Type: application/json

{
  "username": "admin",
  "password": "123"
}

###

POST {{host}}/auth/signup
Content-Type: application/json

{
  "username": "admin",
  "password": "123"
}

###

GET {{host}}/posts
Authorization: Bearer {{token}}


###

POST {{host}}/posts
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Simple Post 3",
  "body": "Content"
}

###

PUT {{host}}/posts
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 1,
  "title": "Simple Data 2",
  "body": "Content 2"
}